"""
Take in an annotated file and apply ACMG standards using the BIAS-2015 algorithm
to classify the variants.

Supported annotators:
  - Nirvana (Illumina Connected Annotations) - default, JSON format
  - VEP (Ensembl Variant Effect Predictor) - JSON format

Use the --annotator flag to specify which annotator was used to generate the input file.

BIAS-2015 requires multiple data files to run. The user must pass these to the algorithm through
a required_paths.json file that tells the algorithm the full path for each of these required files.

The data files can be downloaded from the Bitscopic AWS bucket and unzipped. Then a
required_paths.json file can be made by running the create_new_required_paths_file.py script:

    python3 src/scripts/create_new_required_paths_file.py <file_directory> hg19 hg19_required_paths.json

Alternatively, the required data files can be generated by running the preprocessing.py script.
Please note this takes multiple hours, and will write many GB to disk. It will create the
required files, along with a required_paths.json file.

Examples:
    # Using Nirvana annotated file (default)
    python3 bias_2015.py input.nirvana.json required_paths.json output.tsv

    # Using VEP JSON annotated file
    python3 bias_2015.py input.vep.json required_paths.json output.tsv --annotator vep
"""
import json
import sys
import argparse
import time
import logging
from src.bias_2015 import extract_from_nirvana_json, extract_from_vep_json, bias_dataset_loader, constants
from src.bias_2015.gene_data_loader import build_hgnc_to_gene_data

# Keep track of runtime
start_time = time.time()

# Supported annotators
SUPPORTED_ANNOTATORS = ['nirvana', 'vep']


def parseArgs():
    """
    Parse the command line arguments into useful python objects.  '--' variables are optional
    set_defaults only applies when the argument is not provided (it won't override)
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("annotated_json_file",
                        help="Annotated file (Nirvana .json/.json.gz or VEP .json)")
    parser.add_argument("file_paths_json",
                        help=".json file describing where BIAS additional input files are located")
    parser.add_argument("output_file",
                        help="ACMG classification tsv file")
    parser.add_argument("--annotator",
                        help="The annotator used to generate the input JSON file (default: nirvana)",
                        choices=SUPPORTED_ANNOTATORS,
                        default="nirvana")
    parser.add_argument("--user_classifiers",
                        help="User provided classifiers for each variant")
    parser.add_argument("--skip_list",
                        help="A file listing the ACMG codes to be skipped. One code per line. "
                             "Ex. providing 'PP5' will turn off the ClinVar check for pathogenicity")
    parser.add_argument("--verbose",
                        help="The verbosity level for stdout messages (default WARNING)",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                        default="WARNING")

    options = parser.parse_args()
    logging.basicConfig(level=getattr(logging, options.verbose), format='%(message)s')
    return options


def run_bias(options):
    """
    Load user provided classifications if provided. Load in the data files needed for classification

    Stream through the annotated json file, keeping only one json element in memory at a time.

    Classify each variant one at a time, and write it to the output file as it is being classified.
    """
    # Load the core paths
    config = {}
    with open(options.file_paths_json, 'r') as config_file:
        config = json.load(config_file)

    # User provided classifications (optional)
    variant_to_user_classification = {}
    if options.user_classifiers:
        logging.warning("User classifications detected!")
        with open(options.user_classifiers, 'r') as in_file:
            in_file.readline()
            for line in in_file:
                split_line = line.strip().split("\t")
                chrom, pos, ref, alt = split_line[:4]
                justification = json.loads(split_line[-1])  # The justification is the final column of the output
                variant = (chrom, pos, ref, alt)
                variant_to_user_classification[variant] = justification

    # Check for codes that should be skipped...
    skip_list = set()
    bad_skips = set()
    if options.skip_list:
        with open(options.skip_list, 'r') as in_file:
            for line in in_file:
                user_code = line.strip().lower()  # remove new lines and make it lower case
                if user_code in constants.evaluated_codes:
                    skip_list.add(user_code)
                else:
                    bad_skips.add(user_code)
    if bad_skips:
        bad_skip_str = ", ".join(bad_skips)
        logging.warning("User provided code(s) to skip '%s', however this code(s) is not currently evaluated by BIAS", bad_skip_str)
    if skip_list:
        skip_list = list(skip_list)
        skipped_code_string = ", ".join(skip_list)
        logging.info("Excluding %s code(s) by user request", skipped_code_string)

    # Load in the datasets needed for classification
    ###### NOTE: This step loads a lot of data into memory, it can take up to ~5 GB of RAM ########
    print("Loading data sets...")
    name_to_dataset = bias_dataset_loader.get_name_to_dataset(config)

    end_time = time.time()
    load_time = end_time - start_time
    logging.info("Time to load datasets: %.4f seconds", load_time)

    # Load gene-level data (ClinGen gene-disease validity + gnomAD constraints)
    # This is annotator-independent and serves as the single source of truth
    hgnc_to_gene_data = build_hgnc_to_gene_data(
        config['BS2_clingen_gene_disease_validity_fp'],
        config['PVS1_PM2_BA1_BS1_BS2_gnomad_gene_constraints_fp']
    )

    # Branch based on annotator type
    print(f"Classifying variants using {options.annotator} annotator...")
    if options.annotator == 'nirvana':
        extract_from_nirvana_json.classify_variants(
            options.output_file,
            options.annotated_json_file,
            hgnc_to_gene_data,
            name_to_dataset,
            variant_to_user_classification,
            skip_list
        )
    elif options.annotator == 'vep':
        extract_from_vep_json.classify_variants(
            options.output_file,
            options.annotated_json_file,
            hgnc_to_gene_data,
            name_to_dataset,
            variant_to_user_classification,
            skip_list
        )

    end_time = time.time()
    run_time = end_time - start_time - load_time
    logging.info("Time to classify variants: %.4f seconds", run_time)


def main():
    """
    Go through annotated json and perform ACMG classification
    """
    # Parse arguments
    options = parseArgs()

    # Run the BIAS algorithm
    run_bias(options)

    # Calculate wall runtime
    end_time = time.time()
    total_runtime = end_time - start_time

    # Convert to hours, minutes, seconds
    hours, remainder = divmod(total_runtime, 3600)
    minutes, seconds = divmod(remainder, 60)

    # Build the runtime string dynamically
    runtime_parts = []
    if hours > 0:
        runtime_parts.append(f"{int(hours)}h")
    if minutes > 0:
        runtime_parts.append(f"{int(minutes)}m")
    runtime_parts.append(f"{seconds:.2f}s")  # Seconds are always included
    runtime_str = " ".join(runtime_parts)
    print(f"Finished! Total BIAS-2015 runtime was {runtime_str}")


if __name__ == "__main__":
    sys.exit(main())
