"""
VCEP (Variant Curation Expert Panel) allele-frequency override lookup.

Provides gene-specific AF thresholds for BA1, BS1, and PM2 that come from the
ClinGen Criteria Specification Registry. Classifiers call `get_vcep_rule` at
the top of each AF-based code; if a rule applies, its VCEP threshold/strength
replaces the tiered evaluation. Otherwise the classifier falls through to the
mis_oe × MOI cascade and the flat ACMG default in `constants.ACMG_DEFAULT_AF_CUTOFFS`.

The table is generated by src/preprocessing/generate_vcep_af_cutoffs.py.
"""
from collections import namedtuple


# gnomAD "popmax" is the highest AF across the major continental populations,
# excluding Finnish and Ashkenazi Jewish (bottlenecked) and OTH (mixed). This
# matches gnomAD's own popmax convention. Compute this in the extractors and
# store it on variant.gnomad['popmax'] so VCEP rules can evaluate against it.
POPMAX_POPS = ("afrAf", "amrAf", "easAf", "nfeAf", "sasAf")


def compute_popmax(gnomad_dict):
    """Return the max across major continental population AFs, or None if unavailable."""
    if not gnomad_dict:
        return None
    values = [gnomad_dict[k] for k in POPMAX_POPS if gnomad_dict.get(k) is not None]
    if not values:
        return None
    return max(values)


VcepAfRule = namedtuple("VcepAfRule", [
    "strength",             # StandAlone | Strong | Moderate | Supporting | NotApplicable
    "threshold",            # float, or None for NotApplicable
    "comparator",           # >= | <= | > | <
    "metric",               # raw_af | faf95 | grpmax | popmax
    "population",           # free-text population qualifier
    "min_allele_count",     # int, or 0 if unspecified
    "mode_of_inheritance",  # "" (any) | AR | AD | XL | Mito
    "gn_id",                # e.g., GN021
    "version",              # SVI version string
])


def _variant_mois(variant):
    """Return the set of MoI codes (AR/AD/XL/Mito) for this variant's gene(s)."""
    result = set()
    for entry in getattr(variant, "clingen_gene_validity", []) or []:
        inh = (entry.get("inheritance") or "").lower()
        if "recessive" in inh:
            result.add("AR")
        if "dominant" in inh:
            result.add("AD")
        if "x-linked" in inh or "xlinked" in inh:
            result.add("XL")
        if "mitochond" in inh:
            result.add("Mito")
    return result


def _filter_rules_by_moi(rules, variant):
    """Keep rules whose MoI matches the variant's gene, plus MoI-agnostic rules."""
    mois = _variant_mois(variant)
    return [r for r in rules if not r.mode_of_inheritance or r.mode_of_inheritance in mois]


# Order VCEP strength labels by ACMG weight, strongest first. Used only to pick the
# strongest matching rule when a gene has multiple entries for the same code.
_VCEP_STRENGTH_ORDER = {
    "StandAlone": 5, "VeryStrong": 4, "Strong": 3, "Moderate": 2, "Supporting": 1,
}


def get_vcep_rule(vcep_af_rules, gene_symbol, code, variant):
    """
    Pure data lookup: return the applicable VcepAfRule for this (gene, code, variant),
    or None if there is no VCEP rule that applies.

    Filters candidate rules by the variant's mode(s) of inheritance (from ClinGen)
    when any rule is MoI-specific. When multiple rules remain, returns the strongest
    strength — or the NotApplicable rule if one exists (NotApplicable takes precedence
    so the classifier can suppress the code).

    Contains NO ACMG classification logic — no AF comparisons, no scoring, no
    rationale formatting. All of that belongs in the calling classifier.
    """
    if not vcep_af_rules or not gene_symbol:
        return None
    by_code = vcep_af_rules.get(gene_symbol)
    if not by_code:
        return None
    rules = by_code.get(code) or []
    if not rules:
        return None
    if any(r.mode_of_inheritance for r in rules):
        rules = _filter_rules_by_moi(rules, variant)
        if not rules:
            return None
    for r in rules:
        if r.strength == "NotApplicable":
            return r
    return max(rules, key=lambda r: _VCEP_STRENGTH_ORDER.get(r.strength, 0))
